# CONFIGURATION STATIQUE DU PROXY VIA UN FICHIER YAML.
spring:
  cloud:
    gateway:
      routes:      - id: routeMicroService1_customer-service
        uri: http://localhost:8081/
        predicates:        - Path=/customers/**
      - id: routeMicroService2_inventory-service
        uri: http://localhost:8082/
        predicates:        - Path=/products/**
            
        
        
       
                                        
      